### PR TITLE
Feature/GitHub speed up

### PR DESCRIPTION
**Pull request by martinheidegger**
The changes in the github lookup system of #39 removed the need for having github credentials to get the list of chapters. This pull request removes all traces of the github api calls. Also the requests were changed from serial to parallel. As result the `list` method should have gotten a pretty strong speed up. 

@dinodsaurus You made changes here before, i would be honored if you could take a look at it.

### CODE REVIEW

**Comment by dinodsaurus** [comment]
Awesome PR!!!!!
I refactored only some minor stuff :+1:

**Comment by martinheidegger** [comment]
~~LGTM~~

**Comment by martinheidegger** [comment]
Now looks fine

**Comment by dinodsaurus** [comment]
closes #20

**Pull request merged**
